### ISSUE TITLE
Wrong reference in SessionWarningAsset

### ISSUE THREAD

**Issue by gposse** [mg-code/yii2-session-timeout-warning#1]
SessionWarningAsset includes a dependency to 'mgcode\helpers\HelpersAsset', which is not included in helpers component.

**Comment by mg-code** [comment]
Hello,

do you have minimum stability set to stable in your composer.json?
HelpersAsset currently is in master branch.

I will make a new release of yii2-helpers package, it might help.

**Comment by mg-code** [comment]
I released a new version of yii2-helpers asset. 
It resolved your issue?

**Comment by gposse** [comment]
Solved. Thank you.
