### ISSUE TITLE
widget is not working.

### ISSUE THREAD

**Issue by ajkosh** [mg-code/yii2-session-timeout-warning#4]
I implemented configuration as you said.but nothing is working.

**Comment by mg-code** [comment]
Hi, can you provide more details? 
What is your application configuration?

**Comment by ajkosh** [comment]
@mg-code it is continue running in background as ajax request.
once i login it logout after some seconds
 below is error
Method Not Allowed (#405)
Method Not Allowed. This URL can only handle the following request methods: POST.

this is code i have added 
In Main.php
```
<html lang="<?= Yii::$app->language ?>">
<head>
        <title><?= Html::encode($this->title) ?></title>
        <?= Html::csrfMetaTags() ?>
        <?php $this->head() ?>
        <script>
      var baseUrl = "<?php echo \Yii::$app->request->BaseUrl?>";
       var guest= "<?php echo \Yii::$app->user->isGuest?>";
    </script>
    <?= GATracking::widget([
    'trackingId' => 'UA-27771185-2',
    ]) ?>
    </head>
    <?= \mgcode\sessionWarning\widgets\SessionWarningWidget::widget([
   'warnBefore'=>60,
   'logoutUrl'=>'site/logout',
]); ?>
```
In config file
```
'bootstrap' => [
    'log','app\components\Sociallogin',
    'app\modules\smtp_config\modules\core\components\MailConfig',
    'app\components\YiiConfig',
   

    [
          'class' => \mgcode\sessionWarning\components\SessionWarningBootstrap::className(),
          'initMessages' => true,
      ],
    ],
    'controllerMap' => [
    'session-warning' => [
      'class' => 'mgcode\sessionWarning\controllers\SessionWarningController',
    ],
  ],
'user' => [
            'identityClass' => 'app\modules\user_management\modules\core\models\User',
            'enableAutoLogin' => false,
            'authTimeout' => 3600,
        ],
 'session' => [
            'class' => 'yii\web\Session',
            'cookieParams' => ['httpsonly' => true, 'lifetime' => 3600],
            'timeout' => 3600,
            'useCookies' => true,
        ],
```

**Comment by mg-code** [comment]
@ajkosh probably you have filter that does not allow GET requests. This widget makes GET request to extend session.

**Comment by ajkosh** [comment]
@mg-code no I have no filters .as I searched on google.saying pass data method is equal to post.we can do when it is link but in ur widget how to pass,if I don't use logout url it's is continue sending Ajax request

**Comment by mg-code** [comment]
@ajkosh error message indicates, that you filter requests by method type.
This package does not do that by itself.

**Comment by ajkosh** [comment]
@mg-code but I can't pass filter get.ig I pass this you says it is security issue.logout method should be always post.
